export const ROLE_ADMIN = "ROLE_ADMIN";
export const ROLE_PE_VIEW = "ROLE_PRIVATE_EQUITY_VIEWER";
export const ROLE_PE_EDIT = "ROLE_PRIVATE_EQUITY_EDITOR";

export const ROLE_HF_VIEW = "ROLE_HEDGE_FUND_VIEWER";
export const ROLE_HF_EDIT = "ROLE_HEDGE_FUND_EDITOR";

export const ROLE_RE_VIEW = "ROLE_REAL_ESTATE_VIEWER";
export const ROLE_RE_EDIT = "ROLE_REAL_ESTATE_EDITOR";

export const ROLE_NEWS_VIEW = "ROLE_NEWS_VIEWER";
export const ROLE_NEWS_EDIT = "ROLE_NEWS_EDITOR";

export const ROLE_MM_EDIT = "ROLE_MACROMONITOR_EDITOR";
export const ROLE_MM_VIEW = "ROLE_MACROMONITOR_VIEWER";

export const ROLE_REPORTING_EDIT = "ROLE_REPORTING_EDITOR";

export const ROLE_STRATEGY_RISKS_EDIT = "ROLE_STRATEGY_RISK_MANAGEMENT_EDITOR";

export const ROLE_CORPMEETINGS_EDIT = "ROLE_CORPMEETINGS_EDITOR";
export const ROLE_CORPMEETINGS_VIEW = "ROLE_CORPMEETINGS_VIEWER";

export const ROLE_IC_MEMBER = "ROLE_IC_MEMBER";

export const ROLE_USER_PROFILE_EDIT = "ROLE_USER_PROFILE_EDITOR";

export const ROLE_MONITORING_VIEW = "ROLE_MONITORING_VIEWER";
export const ROLE_MONITORING_EDIT = "ROLE_MONITORING_EDITOR";

export const ROLE_LOOKUPS_VIEW = "ROLE_LOOKUPS_VIEWER";
export const ROLE_LOOKUPS_EDIT = "ROLE_LOOKUPS_EDITOR";

export const ROLE_M2S2_VIEW = "ROLE_M2S2_VIEWER";
export const ROLE_M2S2_EDIT = "ROLE_M2S2_EDITOR";


export const ROLE_HR_DOCS_EDIT = "ROLE_HR_DOCS_EDITOR";