INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(1, 'CASH_EQUIV', 'Cash and Cash Equivalents', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(2, 'INV_P_FUND', 'Investments in Portfolio Funds', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(3, 'ACC_EXP', 'Accrued Expenses and Other', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(4, 'ADM_FEES', 'Administrative Fees', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(5, 'BANK_LOANS', 'Bank Loans', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(6, 'BANK_FEES', 'Banking Fees', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(7, 'FEES_PAY', 'Fees Payable', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(8, 'INTR_EXP', 'Interest Expense', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(9, 'INV_INCOME', 'Investment Income', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(10, 'MNG_FEES', 'Management Fees', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(11, 'M_FUND_EXP', 'Miscellaneous Fund Specific Expense', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(12, 'NET_CHNG', 'Net Change in Unrealized Gains/Losses', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(13, 'NET_REAL_G', 'Net Realized Gains/Losses', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(14, 'ORG_COSTS', 'Organizational Costs', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(15, 'OTHERASSET', 'Other Assets', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(16, 'PERF_FEES', 'Performance Fees', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(17, 'PROF_FEES', 'Professional Fees', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(18, 'RDM_PFNDS', 'Redemptions Receivable from Portfolio Funds', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(19, 'RET_EARN', 'Retained Earnings', '', '', null);
INSERT INTO rep_hf_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(20, 'S_ADV_PFND', 'Subscriptions Advanced to Portfolio Funds', '', '', null);

