INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (1, 'BANK_ACC', 'Bank accounts', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (2, 'SECURITY', 'Security', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (3, 'UNREALGAIN', 'Unrealised Gain', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (4, 'I_R_BONDS', 'Interest receivable - bonds', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (5, 'MNGM_FEE_P', 'Management fee payable', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (6, 'ADM_FEE_P', 'Administration fees payable', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (7, 'AUD_FEE_P', 'Audit fee payable', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (8, 'INT_PAYBL', 'Intercompany Payable', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (9, 'LEGL_FEE_P', 'Legal fees payable', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (10, 'OTHR_PAYBL', 'Other Payables', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (11, 'PROF_FEE_P', 'Professional fee payable', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (12, 'SETUP_EXP', 'Set-up expenses payable', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (13, 'PRTN_CAP', 'Partnership capital - book value', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (14, 'RETN_EARN', 'Retained Earnings', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (15, 'REALS_GLE', 'Realised gain/loss equities', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (16, 'UNRL_OTHSS', 'Unrealised p/l other securities - settled', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (17, 'UNRL_PARTN', 'Unrealised p/l partnership settled', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (18, 'INTRST_IN', 'Interest income', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (19, 'OTHR_IN', 'Other income', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (20, 'MNGM_FEEIN', 'Management fee income', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (21, 'ADM_FEE', 'Administration Fees', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (22, 'AUD_FEEEXP', 'Audit fee expense', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (23, 'COMM_EXP', 'Commission expense', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (24, 'GEN_EXP', 'General expenses', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (25, 'LEGL_FEE', 'Legal fee', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (26, 'ORG_EXP', 'Organisation expense', null, '', null);
INSERT INTO public.rep_re_chart_accounts_type(id, code, name_en, name_kz, name_ru, parent_id) VALUES (27, 'PROF_FEE', 'Professional Fees', null, '', null);


--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(1, 'CASH_EQUIV', 'Cash and Cash Equivalents', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(2, 'INV_P_FUND', 'Investments in Portfolio Funds', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(3, 'ACC_EXP', 'Accrued Expenses and Other', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(4, 'ADM_FEES', 'Administrative Fees', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(5, 'BANK_LOANS', 'Bank Loans', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(6, 'BANK_FEES', 'Banking Fees', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(7, 'FEES_PAY', 'Fees Payable', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(8, 'INTR_EXP', 'Interest Expense', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(9, 'INV_INCOME', 'Investment Income', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(10, 'MNG_FEES', 'Management Fees', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(11, 'M_FUND_EXP', 'Miscellaneous Fund Specific Expense', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(12, 'NET_CHNG', 'Net Change in Unrealized Gains/Losses', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(13, 'NET_REAL_G', 'Net Realized Gains/Losses', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(14, 'ORG_COSTS', 'Organizational Costs', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(15, 'OTHERASSET', 'Other Assets', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(16, 'PERF_FEES', 'Performance Fees', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(17, 'PROF_FEES', 'Professional Fees', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(18, 'RDM_PFNDS', 'Redemptions Receivable from Portfolio Funds', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(19, 'RET_EARN', 'Retained Earnings', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(20, 'S_ADV_PFND', 'Subscriptions Advanced to Portfolio Funds', '', '', null);
--INSERT INTO rep_re_chart_accounts_type(id, code, name_en, name_ru, name_kz, parent_id) VALUES(21, 'SUBS_ADV', 'Subscriptions Received in Advance', '', '', null);

