import { News } from './news';

export const NEWS: News[] = [
    {id: 11, type: 'GENERAL', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''},
    {id: 12, type: 'GENERAL', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''},
    {id: 13, type: 'GENERAL', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''},
    {id: 14, type: 'GENERAL', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''},
    {id: 15, type: 'GENERAL', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''},

    {id: 21, type: 'PE', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''},
    {id: 22, type: 'PE', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''},
    {id: 23, type: 'PE', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''},
    {id: 24, type: 'PE', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''},
    {id: 25, type: 'PE', header: 'Komatsu to buy U.S. mining equipment rival Joy Global for $2.9 billion',
        source: 'Updated 25.07.2016: Reuters, by Chris Gallagher and Taiga Uranaka',
        shortContent: 'Japanese mining equipment maker Komatsu Ltd has agreed to buy U.S. rival Joy Global Inc for $2.9 billion, its biggest-ever acquisition, to boost its clout in the mining industry. The deal, worth $3.7 billion when Joys debt is included, will roughly double the size of Komatsus manufacturing equipment business and give it access to Joys underground mining business. Joy has suffered from its significant exposure to North Americas coal market, which faces regulatory pressure and competition from cheap natural gas. Komatsu said on Thursday that it would acquire 100 percent of the Milwaukee-base',
        content: ''}
];

export const NEWS_MORE: News[] = [
    {id: 101, type: 'GENERAL', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
        source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
        shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
        content: ''},
    {id: 102, type: 'GENERAL', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
        source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
        shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
        content: ''},
    {id: 103, type: 'GENERAL', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
        source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
        shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
        content: ''}
    //{id: 104, type: 'PE', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
    //    source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
    //    shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
    //    content: ''},
    //{id: 105, type: 'PE', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
    //    source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
    //    shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
    //    content: ''},
    //{id: 106, type: 'PE', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
    //    source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
    //    shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
    //    content: ''},
    //{id: 104, type: 'HF', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
    //    source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
    //    shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
    //    content: ''},
    //{id: 105, type: 'HF', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
    //    source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
    //    shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
    //    content: ''},
    //{id: 106, type: 'RE', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
    //    source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
    //    shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
    //    content: ''},
    //{id: 104, type: 'RM', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
    //    source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
    //    shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
    //    content: ''},
    //{id: 105, type: 'SWF', header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
    //    source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
    //    shortContent: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
    //    content: ''}
];


export const NEWS_VIEW: News = {
    id: 777,
    type: 'GENERAL',
    header: 'Verizon Gets Yahoos Web Assets --- Wireless carriers deal to boost Internet role, but excludes stakes in Yahoo Japan, Alibaba',
    source: 'Updated 26.07.2016: The Wall Street Journal (Asia Edition)',
    content: 'Verizon Communications Inc. on Monday said it would buy Yahoo Inc.s web assets for $4.83 billion in cash, ending a drawn-out process for the beleaguered internet company. The price, which includes Yahoos core internet business and some real estate, caps a remarkable fall for the Silicon Valley web pioneer that had a market capitalization of more than $125 billion at the height of the dot-com boom in early 2000. For New York-based Verizon, the deal adds another piece to the digital media and advertising empire it is trying to build. The companies said the purchase is subject to regulatory and',
    shortContent: 'Verizon Communications Inc. on Monday said it'
};